# Generated by Django 6.1.1 on 2026-09-18 08:43

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notechunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=768),
        ),
    ]
