# Generated by Django 6.1.1 on 2026-09-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
